[build]
  base = "frontend"
  command = "npm run build"
  publish = "frontend/build"

[build.environment]
  # Set this in Netlify UI for security instead of here in production
  REACT_APP_API_URL = "https://YOUR_RENDER_SERVICE_URL" # replace after backend deploy

[[redirects]]
  from = "/api/*"
  to = "https://YOUR_RENDER_SERVICE_URL/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify-Proxy"}
