[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://taskify1-lwlb.onrender.com"

[[redirects]]
  from = "/api/*"
  to = "https://taskify1-lwlb.onrender.com/api/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify-Proxy"}
